version: 2.1
orbs:
   pr-comment: benjlevesque/pr-comment@0.1.4
jobs:
   pull_request_comment_test:
      docker:
         - image: cimg/node:lts
      steps:
         - checkout
         - pr-comment/pr-comment:
            comment: |
               GitHubプルリクエストにコメント
               ${CIRCLE_BUILD_URL}
            maxComments: 10
workflows:
   version: 2
   main:
      jobs:
         - pull_request_comment_test