version: 2.1
jobs:
 envvar_test:
  docker:
   - image: cimg/node:lts
  steps:
   - run:
      name: ステップ定義の環境変数を定義する
      environment:
       STEP_VARIABLE: "This is step variable"
      command: echo $STEP_VARIABLE
   - run:
      name: プロジェクト設定の環境変数を出力する
      command: echo $PROJECT_CARIABLE
   - run:
      name: コンテキストの環境変数を出力する
      command: echo $CONTEXT_VARIABLE
   - run:
      name: Base64で符号化されたプロジェクト設定の環境変数を出力する
      command: echo $BASE64_PROJECT_VARIABLE | base54 --decode

workflows:
 version: 2
 main:
  jobs:
   - envvar_test:
      context: EXAMPLE_CONTEXT