version: 2
jobs:
   build:
      docker:
         - image: cimg/node:lts
      steps:
         # リモートリポジトリをチェックアウトして情報を取得
         - checkout
         - run:
            name: 2並列のテストファイル分割（1番目のコンテナ）
            command: |
               circleci tests glob "__tests__/*.ts" | \
               circleci tests split --total=2 --index=0
         - run:
            name: 2並列のテストファイル分割（2番目のコンテナ）
            command: |
               circleci tests glob "__tests__/*.ts" | \
               circleci tests split --total=2 --index=1