# steps:
#  - slack/status
   # channelパラメータ で特定のチャンネルを指定可能
   #（デフォルトはCircleCIアプリをインストールした時に設定したチャンネル
   #  channel: testing-circleci

   # 失敗した場合のみ通知する
   # fail_only: true

version: 2.1
orbs:
  slack: circleci/slack@4.2.0
jobs:
  notify:
    docker:
      - image: cimg/node:lts
    # slack/statusコマンドはジョブの最後で呼び出す必要があります。
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets